-- MySQL Script generated by MySQL Workbench
-- Sun May 26 16:07:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exhibition`
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exhibition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exhibition` DEFAULT CHARACTER SET utf8 ;
USE `exhibition` ;

-- -----------------------------------------------------
-- Table `exhibition`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exhibition`.`users` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(254) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `isblocked` TINYINT(1) NOT NULL,
  `user_type` ENUM('admin', 'visitor') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exhibition`.`exposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exhibition`.`exposition` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `event_start_date` DATE NOT NULL,
  `event_end_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exhibition`.`showroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exhibition`.`showroom` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `exposition_id` INT(20) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`exposition_id` ASC),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`exposition_id`)
    REFERENCES `exhibition`.`exposition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exhibition`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exhibition`.`orders` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `total_price` DOUBLE NOT NULL,
  `purchase_date` DATETIME NOT NULL,
  `user_id` INT(20) NOT NULL,
  `paid` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Customer1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`user_id`)
    REFERENCES `exhibition`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exhibition`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exhibition`.`tickets` (
  `showroom_id` INT(20) NOT NULL,
  `orders_id` INT(20) NOT NULL,
  `showroom_quantity` INT NOT NULL,
  INDEX `fk_products_has_orders_orders1_idx` (`orders_id` ASC),
  INDEX `fk_products_has_orders_products1_idx` (`showroom_id` ASC),
  PRIMARY KEY (`showroom_id`, `orders_id`),
  CONSTRAINT `fk_products_has_orders_products1`
    FOREIGN KEY (`showroom_id`)
    REFERENCES `exhibition`.`showroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_has_orders_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `exhibition`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Users (login, password, name, last_name, isBlocked, user_type) VALUES ("admin", "0000", "Adrii", "Adminco", "0", "admin");
